### ISSUE TITLE
Move over data access pattern from MLDataUtils

### ISSUE THREAD

**Issue by Evizero** [JuliaML/MLDataPattern.jl#1]
Hi @tbreloff. I am in the process of transferring the code. I am flagging you as author of the parts where you were a primary author of. I hope this is ok

**Comment by tbreloff** [comment]
Thanks, though I'm surprised I'm primary author of anything that survived
the several rewrites. Happy to be noted as a collaborator though!

**Comment by Evizero** [comment]
👍 . Yes, well it is not verbatim the same code anymore, but the basic idea and structure remained in a lot of places
