### ISSUE TITLE
eachbatch is not CuArray friendly

### ISSUE THREAD

**Issue by xukai92** [JuliaML/MLDataPattern.jl#33]
```julia
x = cu(rand(2, 10))
x1 = first(eachbatch(x, size=5))
typeof(x1) # => Array{Float32,2}
```

I would expect to get `CuArray{Float32,2}` back, or at least a view there. Is there a way to achieve what I want with the existing code base?

**Comment by johnnychen94** [comment]
taking advantages of `MappedArrays`, you could do things like:

```julia
x_gpu = mappedarray(cu, batchview(x, size=5));
```

the conversion from CPU to CUDA is lazily evaluated.

**Comment by Evizero** [comment]
While the issue has a point I think its worth pointing out that its more common and (aside from toy examples) more useful to not move all the data to the GPU at once. 

Here is an old snippet demonstrating what I mean

```julia
for (batch_x_cpu, batch_y) in eachbatch((train_x ,train_y), batchsize)
    batch_x = KnetArray{Float32}(batch_x_cpu)
    g = costgrad(w, batch_x, batch_y)
    Knet.update!(w, g, lr = lr)
end
```

**Comment by xukai92** [comment]
Thanks @johnnychen94 - `batchview` is what I'm looking for. I wonder how should I go through the doc so that I don't miss things like this?

@Evizero Yes I do this too when data is large. But for cases when I prototype my methods on small datasets (MNIST, CIFAR10), I just prefer move them all to the GPU at once to make the loop a bit faster :)

Thanks for both of you again. I'm closing this issue now.
