### ISSUE TITLE
ERROR: UndefVarError: indmax not defined

### ISSUE THREAD

**Issue by drozzy** [JuliaML/MLDataPattern.jl#51]
Going through the docs https://mldatapatternjl.readthedocs.io/en/latest/documentation/targets.html when I reach this line:
```
targets(indmax, X, obsdim=1)
```
The `indmax` function was never defined up to this point, so we get the error:
```
ERROR: UndefVarError: indmax not defined
```

**Comment by drozzy** [comment]
My understanding is this is some deprecated function in Julia, and now `argmax` is used instead?

**Comment by johnnychen94** [comment]
Correct, `indmax` was a Base function and was removed in v1.0. Glad you have worked this out by yourself, would you mind to update the docs accordingly?

**Comment by drozzy** [comment]
Sure see #52
