### ISSUE TITLE
Make `eachbatch` etc  take an `upto` option

### ISSUE THREAD

**Issue by oxinabox** [JuliaML/MLDataPattern.jl#8]
Usecase:

I don't really care exactly how big my batch's are.
They are normally around ten-thousand item, because that is what it takes to make TensorFlow/GPU workout on my system to give good speed.

What I don't want is to:
 - waste items -- particularly when these are batches of test(/dev) data I am evaluating on
 - Have more than about 50_000 items, because then I will run out of RAM.

So what I propose is an on option, call it `upto` (or `flexible`),
which if set, causes the true batch size to be calculated as the largest factor of `n_obs` that is less than the size that is given by the `size` or `count` arguments.
Which should probably throw a warning if this size is `1`

**Comment by Evizero** [comment]
Not sure I fully understand, can you elaborate with some pseudo code of what you'd expect to happen differently

**Comment by oxinabox** [comment]
Eg:


If `upto` is set, the the batch size, will be set to the largest divisor of n_obs,
that is no larger than `size` 

Eg for `n_obs = 210`
The divisors of 210 are: 1, 2, 3, 5, 6, 7, 10, 14, 15, 21, 30, 35, 42, 70, 105, and 210

```julia
julia> length(first(eachbatch(1:210, size=20)))
INFO: The specified values for size and/or count will result in 5 unused data points
20

julia> length(first(eachbatch(1:210, size=20, upto=true)))  
15 #Fake output for mockup


julia> length(first(eachbatch(1:210, size=25)))
INFO: The specified values for size and/or count will result in 10 unused data points
25


julia> length(first(eachbatch(1:210, size=25, upto=true)))
21 #Fake output for mockup
```

So if `upto` is true, it gives the largest batch possible, that evenly divides the number of observations (without remainder),

**Comment by Evizero** [comment]
I see what you mean. Yes that is a good use case
